---
# tasks file for ansible-role-openstack-cinder-volume

- apt: name="{{ item }}"
  with_items:
    - cinder-volume
  when: not ansible_unit_test

- name: Create Intall Directory
  file: state=directory recurse=yes path="{{ ansible_unit_test_prefix_dir }}/etc/cinder/"

- name: Templates a file out to a remote server.
  template: src="cinder.conf.j2" dest="{{ ansible_unit_test_prefix_dir }}/etc/cinder/"
  notify: restart cinder-volume

- service: name="cinder-volume" state=started enabled=true
